language: c

services:
- docker

env:
  global:
# https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1802718
# and/or travis docker image(s) not having enabled 'deb-src' lines
# contrary to docker documentation -> https://docs.docker.com/samples/library/ubuntu/
# NB At time of writing 2018-11-11: artful doesn't really need this FIX_APT_CONFIG, but no harm in applying it
# TRAVIS BROKEN
#   - FIX_APT_CONFIG="sed -i '/^#\sdeb-src /s/^#//' /etc/apt/sources.list"
# The common extra dependencies required beyond the default distribution 'build-dep'
   - COMMON_DEPS="gtk-doc-tools yelp-tools libgeoclue-2-dev nettle-dev liboauth-dev libzip-dev libglib2.0-dev-bin"
  matrix:
# NB Ubuntu 16.04 doesn't have a new enough geoclue so simply disable using it
   - BUILD_IMG=ubuntu:16.04 DEPS=libmapnik-dev OPTS="--disable-geoclue"
   - BUILD_IMG=ubuntu:18.04
# Docker images previously (temporarily?) available but have vanished:
#  - BUILD_IMG=ubuntu:18.10
#  - BUILD_IMG=ubuntu:19.04
   - BUILD_IMG=ubuntu:19.10
# Test basic levels of some configure options
# Use the latest LTS version for these
   - BUILD_IMG=ubuntu:18.04 DEPS="libexif-dev" OPTS="--with-libexif"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-bzip2"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-magic"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-mapnik"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-mbtiles"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-nettle"
   - BUILD_IMG=ubuntu:18.04 OPTS="--disable-zip"

script: docker run --rm=true -v $HOME:$HOME:rw $BUILD_IMG /bin/sh -c "sed -i '/^#\sdeb-src /s/^#//' /etc/apt/sources.list && apt-get update && apt-get build-dep --yes viking && apt-get install --yes $COMMON_DEPS $DEPS && cd $PWD && ./autogen.sh $OPTS && make -j && make -j check && make install"
# Further packages are installed as these are new dependencies for the latest source code, compared to the dependencies listed in the distribution version (`apt-get build-dep` always refers to the version which is built for the OS rather than the up-to-date source)
